Setup encode databases
hotosm/Drone-TM pull request #10
Opened 2024-06-26 06:07 UTC by Pradip-p

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation
- [ ] 🧑‍💻 Refactor
- [ ] ✅ Test
- [ ] 🤖 Build or CI
- [ ] ❓ Other (please specify)

## Related Issue
N/A

## Describe this PR

This PR introduces a new  encode database connection implementation and feature for creating projects  using a raw SQL query. It includes the following changes:
- Update an endpoint `/create_project` to handle project creation.
- Update an endpoint `/{project_id}/upload-task-boundaries` to upload task boundaries
- Utilizes raw SQL queries for inserting and fetching project data.
- Implements a new encode databases connection.

## Screenshots
![Screenshot from 2024-06-26 11-48-34](https://github.com/hotosm/Drone-TM/assets/54197382/4f4cff24-567d-454e-8df9-7c2e396e1b68)
![Screenshot from 2024-06-26 11-50-57](https://github.com/hotosm/Drone-TM/assets/54197382/9151b886-e420-4e8e-b429-28557a466299)

## Alternative Approaches Considered

- Considered using an ORM for project creation but opted for raw SQL for performance reasons and finer control over the query execution.

## Review Guide

- **Testing the Change**: To test this change, you can send a POST request to the `/create_project` endpoint with the necessary project metadata.
- **Code to Review**: Focus on the endpoint implementation and the database connection/session management logic.

2024-06-30 13:52 UTC, nrjadkry commented
@Pradip-p This Pull request has a merge conflicts. Will you resolve them.

2024-07-01 06:02 UTC, nrjadkry approved these changes

2024-07-01 06:02 UTC, merged

2024-07-01 07:54 UTC, spwoodcock approved these changes

2024-07-01 07:54 UTC, spwoodcock commented on src/backend/app/projects/project_crud.py
> +    db:Database,
Is this type correct?

It seems like it's probably a SessionLocal object, but I could be wrong

2024-07-01 07:56 UTC, spwoodcock requested changes

2024-07-01 07:56 UTC, spwoodcock commented on src/backend/app/projects/project_crud.py
> +            query = f""" INSERT INTO tasks (project_id,outline,project_task_index) VALUES ( '{project_id}', '{wkblib.dumps(shape(polygon["geometry"]), hex=True)}', '{index + 1}');"""
Definitely don't use f-strings to insert values into the db. It probably opens us up to SQL injection attacks.

I'm sure there is probably a recommended way from the Databases docs.

2024-07-01 07:56 UTC, spwoodcock commented on src/backend/app/users/user_crud.py
> +    query = f"SELECT * FROM users WHERE username = '{username}' LIMIT 1;"
Please update all f-string usage for SQL 🙏